/**
 * Cloudflare Pages Function
 * Intercepts requests to /js/config.js and injects the environment variable.
 * This removes the need for a build step.
 */
export async function onRequest(context) {
    const apiKey = context.env.GOOGLE_MAPS_API_KEY || '';

    const jsContent = `/**
 * Application Configuration
 * Dynamically generated by Cloudflare Functions
 */
const APP_CONFIG = {
    GOOGLE_MAPS_API_KEY: '${apiKey}'
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = APP_CONFIG;
}
`;

    return new Response(jsContent, {
        headers: {
            "content-type": "application/javascript;charset=UTF-8"
        }
    });
}
